### ISSUE TITLE
The modified gym is not working

### ISSUE THREAD

**Issue by SupposeRay** [asbroad/koopman_operator_model_learning#1]
Hi, I was trying to implement the Koopman operator after reading the corresponding paper but came to encounter some issues.

First, I followed every step in the instruction: creating a ROS workspace, downloading the repositories (Koopman Operator and modified Gym), compiling the scripts, and running the launch files. Then I got errors popped up showing everything of the Gym was missing.
After that, I tried installing the original Gym first, did the same things above, and got this error log.

```
    from Box2D.b2 import (edgeShape, circleShape, fixtureDef, polygonShape, revoluteJointDef, contactListener)
ImportError: No module named b2
Shutting down
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 466, in signal_shutdown
    h()
  File "/home/ray/ros_ws/src/koopman_operator_model_learning/scripts/collect_observations.py", line 157, in shutdown_hook
    self.history = np.zeros((17, self.total_steps))
AttributeError: LunarLander instance has no attribute 'total_steps'
```

I checked the Python library and found that only Python 3.5 has the **b2** module in **Box2D**, but Python 2.7 doesn't have. However, I am using ROS Kinetic, whose default python version is 2.7.

Appreciate it.

**Comment by SupposeRay** [comment]
btw, I'm using Ubuntu 16.04

**Comment by asbroad** [comment]
Hey @SupposeRay, sorry for the slow response.  This may be a little hard to debug from afar, but my notes say that I was using Python 2.7 as well, so I think it should be fixable.  How did you install pybox2d?  I would recommend removing your current install and trying to follow the "Build from source: Linux" instructions from the following git repo: https://github.com/pybox2d/pybox2d/blob/master/INSTALL.md

Alternatively, if you think Python 3.5 is the answer, you can try setting your PYTHONPATH and making sure that you don't point to 2.7 anywhere.

**Comment by SupposeRay** [comment]
Thanks @asbroad ! I think I should try building from the source and see if it's gonna work.

**Comment by asbroad** [comment]
Sounds good, good luck! I'll close this issue for now, but feel free to reach back out.
